### ISSUE TITLE
MainPicture bitrate maximum exceeds DCI maximum (250.0 Mb/s) calculation?

### ISSUE THREAD

**Issue by fgrivel** [wolfgangw/digital_cinema_tools_distribution#24]
Hi,

The following Error appears with dcp_inspect v1.2015.01.02
"MainPicture bitrate maximum 260.48 Mb/s exceeds DCI maximum (250.0 Mb/s)"

I've always choosen a bitrate of 250 Mb/s when I created DCPs so I was wondering how do you get the 260.48 value?

thx

**Comment by wolfgangw** [comment]
You can check with ```asdcp-info -r <path to mainpicture asset file>```.

Which encoding app did you use?

**Comment by fgrivel** [comment]
We used MIST from Marquise Tech to encode.

The result with asdcp is:
Max BitRate: 260.48 Mb/s
Average BitRate: 165.53 Mb/s
Bitrate 260 exceeds maximum 250 (see option -r).
Program stopped on error.

Does our encoder exceed the max. bitrate whereas it is not supposed to?

The DCP concerned is playing from 2 years without problem, I hope DCP servers can play higher bitrate than the 250 Mb/s limit.

**Comment by fgrivel** [comment]
Shouldn't this be an hint rather than an error?

**Comment by wolfgangw** [comment]
Can you please run

```klvwalk <path to asset file in question> > klvwalk.txt # note the > klvwalk.txt```

and send the result (```klvwalk.txt```)?

Currently dcp_inspect uses asdcplib's estimated value for Max BitRate. asdcplib takes the largest frame and multiplies with ``ÈditRate```. Of course that largest frame might be surrounded by significantly smaller frames. So we do need a better mechanism, absolutely.

That said: Keep in mind that some systems out there have been designed a long time ago -- when 250 Mb/s sustained might still have been a bit of a stretch. 2 years distribution without any issues does not necessarily mean that there won't be that one legacy system which is just waiting to explode for you :)

Btw, for 2K 2D compositions 250 Mb/s is too much anyway. Of course test but anything between 150 and 190 Mb/s will give you very good results.

250 Mb/s is a specified maximum and I'd take it seriously. Thus the error-class message.
