### ISSUE TITLE
Multi language subtitles Naming convention

### ISSUE THREAD

**Issue by fgrivel** [wolfgangw/digital_cinema_tools_distribution#25]
Hi again,

using dcp_inspect v1.2015.01.02 

Regarding the naming convetilention for multi-language subtitles, dcp_inspect does not recognize the language part of the ContentTitleText if you have more than one subtitles language.

See appendix 1 of Naming Convention
http://digitalcinemanamingconvention.com/appendix_1.asp

for example, I got FR-IT-TR language for my composition playlist and it says the language part is missing. If I have FR-IT, it match.

**Comment by wolfgangw** [comment]
Yes indeed, the naming convention parser needs some love. It's not very high on the list but I do find its various mishaps quite annoying as well. One of these days ... Ok?

**Comment by wolfgangw** [comment]
Fixed by removing the feature (naming checks) for the time being.
