### ISSUE TITLE
Installation: rbenv

### ISSUE THREAD

**Issue by wolfgangw** [wolfgangw/digital_cinema_tools_distribution#26]
From Fabrizio (@ fabriziocarraro):

I've problems with the setup when it tries to install rbenv. It says:

fatal: unable to connect to github.com
github.com[0: 192.30.252.130]: errno=Connection refused
rbenv: failed to clone repository. Try again later

I tried many times in the last months. One one machine running opensuse I manage to install manually rbenv, but with a lot of unresolved conflicts. Dcp_inspect works but with some limitation.
I'm trying again with a fresh installation of opensuse and ubuntu 12.4, but I cannot manage to complete the installation script
I hope you can help me.
Regards
Fabrizio

**Comment by wolfgangw** [comment]
Odd. A simple ```git clone git://github.com/sstephenson/rbenv.git``` works just fine here. Means the repo exists and github is spitting it out, too.

Installation of ```rbenv``` is not the first net-contact in the setup script so I am assuming you do have network. Could you please post the complete output of the setup script?

**Comment by lucasiacca** [comment]
I'm also having that kind of issues.
I'm actually working on Ubuntu 14.04 ... that is maybe the mistake?

ruby-build: Failed to clone repository. Try again later
rbenv: version `2.1.5' not installed
rbenv: Required ruby not installed
Ruby: Installing ... This will take a while (~5 minutes)
rbenv: no such command `install'
Ruby: Failed to install requested version
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
Nokogiri: Failed to install rtequired gem nokogiri
openjpeg: OK
asdcplib: OK (1.12.58)
Cloning into 'digital_cinema_tools_distribution'...
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection refused

Digital cinema tools distribution: Failed to clone repository. Try again later
Digital cinema tools distribution: Failed to update /home/proyeccion/.digital_cinema_tools/.bin. Repository missing
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
dcp_inspect: Failed to install nice-to-have gem ttfunk. This is not a critical error
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
cinemaslides: Failed to install required gem highline. Try again later
cinemaslides: CINEMASLIDESDIR is set. OK
cinemaslides: CINEMACERTSTORE is set. OK
Local certificate store: Generating example certificates ...
digital-cinema-tools-setup: line 862: /home/proyeccion/.digital_cinema_tools/.bin/make-dc-certificate-chain.rb: No such file or directory


Thanks!

**Comment by wolfgangw** [comment]
Just tested this (again and not the first time over) on a fresh Ubuntu 14.04.2 installation: Setup runs through without a glitch, exactly as expected.

You seem to have network issues. And apparently you ran setup multiple times (which is okay). Did you ```exec $SHELL``` the first time around?
