### ISSUE TITLE
Output inspect result as JSON

### ISSUE THREAD

**Issue by oktav** [wolfgangw/digital_cinema_tools_distribution#29]
Are there any plans to have dcp_inspect output the result to a more structured format instead of text?

**Comment by wolfgangw** [comment]
Yeah, would be nifty, indeed. Right now it's just a frigging blob which isn't even human-readable - let's be honest :)

It's on the Bigger List.

**Comment by wolfgangw** [comment]
@oktav stuff is in the works which will allow for better flexibility wrt output formats and add KDM inspection/relations.

Closing this specific issue for now.
