### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by DanielfromBX** [wolfgangw/digital_cinema_tools_distribution#33]
I am using cinema_tools on Ubuntu 16.04
From recently I get the following errors message
"
Required command asdcp-info not found. Please run digital-cinema-tools-setup or install the missing component manually
Required command asdcp-unwrap not found. Please run digital-cinema-tools-setup or install the missing component manually
Required command kmuuidgen not found. Please run digital-cinema-tools-setup or install the missing component manually
"

I try to run cinema tools setup and get also some error message
"
openjpeg: failled to download tarball
asdcplib: download.cinecert.com/asdcpli seems to be down
"
Manually I can access to cinecert download page. But I don't know what to do after i have download the package.

Thank you for you help.

Regards

**Comment by FbjP** [comment]
Hi there,

Same issue here (Ubuntu server 10.04.05), it seems that there's a problem with the Cinecert's website certificate, which can't be validated by an approved authority, and it prevents asdcplib download.
I tried to install it manually, without success.

Any way to override the website certificate check in the script ?

Best regards,

**Comment by s0faking** [comment]
check #32

**Comment by FbjP** [comment]
Just did the same thing, and it worked.

**Comment by wolfgangw** [comment]
This issue is resolved. At the time CineCert had provided secured downloads (which is a good thing) and then changed back. This went on while I was changing the setup script to allow for secured (and verified) download of asdcplib.

Thanks, people, for the workaround and taking care of each other there :)
