### ISSUE TITLE
install issue with asdcplib (ubuntu 18 / openssl 1.1.0)

### ISSUE THREAD

**Issue by carlschuurbiers** [wolfgangw/digital_cinema_tools_distribution#36]
Install issue in Ubuntu18 (openssl 1.1.0)
asdcplib won't install correctly, apparrently some compatibiliy problem with openssl 1.1.0?
Will try downgrading openssl to 1.0.2

Transcript:

M_prng.cpp: In function 'void Kumu::Gen_FIPS_186_Value(const byte_t*, ui32_t, byte_t*, ui32_t)':
KM_prng.cpp:219:10: error: aggregate 'BIGNUM c_2powb' has incomplete type and cannot be defined
   BIGNUM c_2powb, c_2, c_b;
          ^~~~~~~
KM_prng.cpp:219:19: error: aggregate 'BIGNUM c_2' has incomplete type and cannot be defined
   BIGNUM c_2powb, c_2, c_b;
                   ^~~
KM_prng.cpp:219:24: error: aggregate 'BIGNUM c_b' has incomplete type and cannot be defined
   BIGNUM c_2powb, c_2, c_b;
                        ^~~
KM_prng.cpp:220:3: error: 'BN_init' was not declared in this scope
   BN_init(&c_2powb);  BN_init(&c_2);  BN_init(&c_b);
   ^~~~~~~
KM_prng.cpp:220:3: note: suggested alternative: 'BN_print'
   BN_init(&c_2powb);  BN_init(&c_2);  BN_init(&c_b);
   ^~~~~~~
   BN_print
KM_prng.cpp:248:14: error: aggregate 'BIGNUM bn_tmp' has incomplete type and cannot be defined
       BIGNUM bn_tmp, bn_xkey, bn_x_n;
              ^~~~~~
KM_prng.cpp:248:22: error: aggregate 'BIGNUM bn_xkey' has incomplete type and cannot be defined
       BIGNUM bn_tmp, bn_xkey, bn_x_n;
                      ^~~~~~~
KM_prng.cpp:248:31: error: aggregate 'BIGNUM bn_x_n' has incomplete type and cannot be defined
       BIGNUM bn_tmp, bn_xkey, bn_x_n;
                               ^~~~~~
Makefile:1139: recipe for target 'KM_prng.lo' failed

**Comment by brocky27** [comment]
I'm having the same issue, apparently, it's to do with OpenSSL https://stackoverflow.com/questions/42292027/aggregate-bignum-foo-has-incomplete-type-and-cannot-be-defined

**Comment by shagabutdinov** [comment]
Have this issue; any update on this?

**Comment by wolfgangw** [comment]
Essentially the issue is triggered by openssl's API changes: [](url)https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes

As far as I can tell they're doing the right thing. Alas, along the way, they broke a bunch of stuff and distributions/applications would need to follow suit. asdcplib hasn't yet. I'll ask.

Carl, downgrading openssl on Ubuntu 18.04 is probably non-trivial; lots of broken glass along that path. Have you tried?

For now the cold hard truth is that Ubuntu 18.04 and other distros which bring openssl 1.1.0 are not supported.

**Comment by carlschuurbiers** [comment]
Downgrading OpenSSL is indeed non-trivial. After reading about other people trying to do this, I decided to abandon that path. Too "non-trivial" for me ;-)

**Comment by DanielBlackburn** [comment]
Is there any update to this, or any possible workarounds to try?  I'm having this same issue on Raspbian Stretch. I'm not sure I like the broken glass route but I don't want to have to reinstall Raspbian Jessie if I can avoid it. 

As a side note the setup script said unrecognised OS on Raspbian.  I just hardcoded it to Debian and that worked, other than this issue with asdcplib.

**Comment by wolfgangw** [comment]
Today's eb9eeefcad3967cb05bf72f8409b0c85a7a8d2fe should fix this.
