### ISSUE TITLE
Infinite loop in .bashrc

### ISSUE THREAD

**Issue by rainerkohlberger** [wolfgangw/digital_cinema_tools_distribution#40]
Putting
`source $HOME/.bash_profile`
into .bashrc created an infinite loop when login in via SSH for me. I wasn't able to login to my machine (Ubuntu 20.04) anymore. This really should be done in a different way. Thanks.

**Comment by wolfgangw** [comment]
Agreed, quite unfortunate. Tried and failed to resolve this just now. Will look into it again.

**Comment by wolfgangw** [comment]
Fixed in latest - not using ~/.bash_profile anymore.
