### ISSUE TITLE
digital-cinema-tools-setup broken due to policy changes in github

### ISSUE THREAD

**Issue by kjaernet** [wolfgangw/digital_cinema_tools_distribution#45]
As of 15. March 2022. Digital Cinema Tools no longer builds straight out of the box due to this policy change: https://github.blog/2021-09-01-improving-git-protocol-security-github/

The fix is to replace `git://` with `https://` inside the digital-cinema-tools-setup file where the script is cloning repositories.

**Comment by akayueh** [comment]
https://github.com/wolfgangw/digital_cinema_tools_distribution/pull/46

I have request a pull

**Comment by herrschmidt** [comment]
> As of 15. March 2022. Digital Cinema Tools no longer builds straight out of the box due to this policy change: https://github.blog/2021-09-01-improving-git-protocol-security-github/

Just ran into the same errors. Is there a workaround to install it right now?

**Comment by mivk** [comment]
Unfortunately, it's not enough. See https://github.com/wolfgangw/digital_cinema_tools_distribution/pull/46#issuecomment-1102852132

**Comment by herrschmidt** [comment]
Hm, too bad! Thank you

**Comment by wolfgangw** [comment]
@kjaernet @akayueh @herrschmidt @mivk this is considered fixed with the caveat of possibly having offending git remotes hanging around in older installations. If you guys can, remove your ```~/.digital_cinema_tools``` directory and run
```wget https://git.io/digital-cinema-tools-setup && bash digital-cinema-tools-setup```
to get the latest and brightest.

Sorry for the hassle.
