### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by manuelbascoy** [wolfgangw/digital_cinema_tools_distribution#47]
Hello everyone, 

I am having the following issue when installing, it never happened to me in all the years I have been using DCP_INSPECT, at the end of the process, the terminal displays the following: 

TCloning into 'digital_cinema_tools_distribution'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out

Digital cinema tools distribution: Failed to clone repository. Try again later
Digital cinema tools distribution: Failed to update /root/.digital_cinema_tools/.bin. Repository missing
Fetching ttfunk-1.7.0.gem
Successfully installed ttfunk-1.7.0
Parsing documentation for ttfunk-1.7.0
Installing ri documentation for ttfunk-1.7.0
Done installing documentation for ttfunk after 0 seconds
1 gem installed
dcp_inspect: Nice-to-have gem ttfunk OK
Fetching highline-2.0.3.gem
Successfully installed highline-2.0.3
Parsing documentation for highline-2.0.3
Installing ri documentation for highline-2.0.3
Done installing documentation for highline after 2 seconds
1 gem installed
cinemaslides: Required gem highline OK
Tab completion: Setting fastpath to on
digital-cinema-tools-setup: Keeper still borked

There were errors:
Error: ruby-build: Failed to clone repository. Try again later
Error: Ruby: Failed to install requested version
Error: Nokogiri: Could not test Nokogiri C14N support (Required ruby version not found)
Error: Digital cinema tools distribution: Failed to clone repository. Try again later
Error: Digital cinema tools distribution: Failed to update /root/.digital_cinema_tools/.bin. Repository missing
Error: digital-cinema-tools-setup: Keeper still borked

Anyone having the same problem? any help is appreciated.

best, 

Manuel

**Comment by manuelbascoy** [comment]
I just solved some Ruby related problems, but the final step is still failing, it's something related to the repository:

There were errors:
Error: Digital cinema tools distribution: Failed to clone repository. Try again later
Error: Digital cinema tools distribution: Failed to update /home/produccion/.digital_cinema_tools/.bin. Repository missing
Error: digital-cinema-tools-setup: Keeper still borked

**Comment by wolfgangw** [comment]
Manuel, sorry for the late response. With the latest fixes in master this issue should be resolved. Please try again from
`wget https://git.io/digital-cinema-tools-setup && bash digital-cinema-tools-setup`

**Comment by manuelbascoy** [comment]
Hi Wolfgang, 

Thank you very much for your reply. I just tried this command, but I get a new error, am I doing something wrong?, sorry I am not a linux expert, I am using Ubuntu 20.04.5 LTS. 

Thank you very much for all your work!, 

Best, 
Manuel

asdcplib: OK (2.10.31)
Cloning into 'digital_cinema_tools_distribution'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out

Digital cinema tools distribution: Failed to clone repository. Try again later
Digital cinema tools distribution: Failed to update /home/produccion/.digital_cinema_tools/.bin. Repository missing
dcp_inspect: Nice-to-have gem ttfunk OK
cinemaslides: Required gem highline OK
set show-all-if-ambiguous on
Tab completion: Fastpath set to on. Leaving untouched. OK
digital-cinema-tools-setup: Keeper still borked

There were errors:
Error: Digital cinema tools distribution: Failed to clone repository. Try again later
Error: Digital cinema tools distribution: Failed to update /home/produccion/.digital_cinema_tools/.bin. Repository missing
Error: digital-cinema-tools-setup: Keeper still borked

digital-cinema-tools-setup: Done

**Comment by wolfgangw** [comment]
@manuelbascoy If you can, remove your ```~/.digital_cinema_tools``` directory and run
```wget https://git.io/digital-cinema-tools-setup && bash digital-cinema-tools-setup```
for a clean initial setup.
