### ISSUE TITLE
Installation Fails on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by BSE97** [wolfgangw/digital_cinema_tools_distribution#49]
Hi,

unfortunately it's not working to install the digital cinema tools on ubuntu 22.04.3 as of now.
I managed to get it to work a few weeks ago but right now, it's full of errors.
This has been done on a clean install:

**First try:**

apt-get: OK
grep: /home/sysadm/.bash_profile: No such file or directory
bashrc: Adding /home/sysadm/.digital_cinema_tools/.bin to PATH
rbenv: Installing
Cloning into '/home/sysadm/.digital_cinema_tools/.lib/.rbenv'...
remote: Enumerating objects: 3253, done.
remote: Counting objects: 100% (403/403), done.
remote: Compressing objects: 100% (212/212), done.
remote: Total 3253 (delta 226), reused 308 (delta 179), pack-reused 2850
Receiving objects: 100% (3253/3253), 661.87 KiB | 1.87 MiB/s, done.
Resolving deltas: 100% (2016/2016), done.
rbenv: Command 'rbenv' not found

**Second Try:**
afterwards I've rerun the install script, but we still have errors:
rbenv is now installed at least

There were errors:
Error: rbenv: PATH does not include rbenv bin dir
Error: Ruby: Failed to install ruby (Required command rbenv not found)
Error: Nokogiri: Failed to install Nokogiri (Required command gem not found)

**Third Try:**
ruby is installing finally, it seems to be compiling from the sources.

**Comment by BSE97** [comment]
The installation installed ruby 3.2.2 which broke some applications for me. The 2.6.1 version needs to be installed manually.

**Comment by wolfgangw** [comment]
Thanks for the feedback. Touched it, broke it - sorry for the hassle.

I am seeing the same problem (```Command 'rbenv' not found```). Working on it.

**Comment by wolfgangw** [comment]
Fixed.

**Comment by BSE97** [comment]
Thank you, the issue is fixed. I didn't realize that the ruby version upgrade was intentional.
Everything works fine for me now.
